name: spa_booking
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  syncfusion_flutter_datepicker: ^19.2.62
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.8
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  #login with google
  google_sign_in: ^5.2.4
  http: ^0.13.4
  get: ^4.6.1
  jwt_decode: ^0.3.1
  datetime_picker_formfield: ^2.0.0
  font_awesome_flutter: ^8.2.0
  fluttertoast: ^8.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/spa.db

#   fonts:
#     - family: Roboto
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
